Activate news and member factories
easysoftware/ryspec pull request #9
Opened 2019-04-02 07:23 UTC by Joas1988

2019-04-02 08:17 UTC, luk4s requested changes
* Please add new factories to tests. 
* Please follow code style used in ryspec

2019-04-02 08:17 UTC, luk4s commented on spec/factories/project.rb
> +      FactoryGirl.create_list :member, evaluator.number_of_members, :project => project, :roles => [FactoryGirl.create(:role)]
Do not combine hash styles. Use prefer 1.9
https://rubocop.readthedocs.io/en/latest/cops_style/#stylehashsyntax

2019-04-02 08:17 UTC, luk4s commented on spec/factories/members.rb
>  FactoryBot.define do
Missing test for this Factory 
(spec/factory_spec.rb)

2019-04-02 08:17 UTC, luk4s commented on spec/factories/news.rb
> +  factory :news do
missing test for this Factory
(spec/factory_spec.rb)

2019-04-03 11:09 UTC, luk4s requested changes
I think that this will not work. Because `user` is not defined on project

2019-04-03 11:09 UTC, luk4s commented on spec/factories/project.rb
> +        project.add_default_member(user)
Missing test for this line.

2019-04-04 12:09 UTC, Joas1988 commented
Member changes reverted, Redmine logic for creating new projects counts on setting environment that is not currently modeled by factories, so It's better to solve explicitly in specs.

2019-04-04 12:22 UTC, luk4s approved these changes

2019-04-05 09:26 UTC, merged